<Project>
  
  <!-- Solution target framework versions -->
  <PropertyGroup>
    <DotNetTargetFramework>net8.0</DotNetTargetFramework>
  </PropertyGroup>

  <!-- Project default settings -->
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <!-- Signing details -->
  <PropertyGroup>
    <Authors>Antti Veikkolainen</Authors>
    <RepositoryUrl>https://github.com/Av3boy/SharpEngine</RepositoryUrl>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <GenerateNuGetPackages>true</GenerateNuGetPackages>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup>
    <SilkVersion>2.22.0</SilkVersion>
  </PropertyGroup>
  
</Project>