<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(DotNetTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpEngine.Rest\SharpEngine.Rest.csproj" />
    <ProjectReference Include="..\SharpEngine.Telemetry\SharpEngine.Telemetry.csproj" />
  </ItemGroup>

</Project>
